"use strict";

try{
    //x = 10;
    //miFuncion();
    let x = 10;
}
catch(error){
    console.log(error);

}
//Opcional
finally {
    console.log('Termina la revision de errores')
}
console.log('continuamos...')